### ISSUE TITLE
iOS 15.5 Example purchase-tester App Stuck in Blank Screen

### ISSUE THREAD

**Issue by bartan34** [RevenueCat/purchases-capacitor#100]
Hello there! Our team is currently facing an issue while attempting to migrate to the new version of the 'purchases-capacitor' plugin. While our Android app seamlessly integrates with the new version, our iOS app encounters problems running on iOS 15.5 and iOS 15.7. We decided to investigate further by checking if the same issue arises in the example app, and indeed, we found the same problem there as well.

## Expected Behavior
We expect the example app to run smoothly on iOS 15.5 without any issues.

## Current Behavior
However, when we try to run the example app on an iOS device, the build process succeeds, but the app gets stuck on a blank screen with error appearing in the output.

## Steps to Reproduce
1. Install the latest version of the purchases plugin
2. Run the app on device/simulator with an iOS 15.5 version

## Context (Environment)

```
Installed Dependencies:

  @capacitor/cli: 5.2.3
  @capacitor/core: 5.2.3
  @capacitor/android: 5.2.3
  @capacitor/ios: 5.2.3
```
```
System:

   NodeJS : v16.20.1
   npm    : 8.19.4
   OS     : macOS Unknown
```
```
Devices:

iOS: 15.5
iOS: 15.7
```

## Detailed Description
There was no issue while running the both example app and our app with android devices and devices with iOS 16. However after the build succeeds on iOS 15.5, the Xcode output of the example app displays the following message:

`2023-09-05 16:13:15.331114+0300 App[860:50726] [ViewportSizing] minimumViewportInset cannot be larger than frame
`

**Comment by tonidero** [comment]
Hi @bartan34, we've just released `6.0.0-beta.2` that fixes this issue. Going to close this but please let us know if you run into issues! Thanks for reporting it!
