### ISSUE TITLE
Nothing happens with purchaseStoreProduct on iOS

### ISSUE THREAD

**Issue by TheotimeColin** [RevenueCat/purchases-capacitor#101]
Hi ! First of all, thank you for making this ❤️

I'm able to display products correctly from the App Store, but the method `purchaseStoreProduct` never returns or logs anything. I'm using `@capacitor/core 5.2.3` with a `Nuxt 3.6.5` app.

The iOS payment popin never appears (it was working when I used `cordova-plugin-purchase`). I tested this on the simulator and my physical Iphone X. 

Here's my code:

```js
export const products: Ref<PurchasesStoreProduct[]> = ref([])

export const initIAP = async () => {  
  if (!Capacitor.isNativePlatform()) return 

  try {
    Purchases.configure({
      apiKey: 'XXX',
      observerMode: false
    })

    const { products: fetchedProducts } = await Purchases.getProducts({
      productIdentifiers: ['supporter_v2_one_month']
    })

    products.value = fetchedProducts
  } catch (e) {
    console.error(e)
  }
}

export const purchaseProduct = async (product: PurchasesStoreProduct) => {
  try {
    console.log('purchase')
    console.log(product)

    const response = await Purchases.purchaseStoreProduct({
      product
    })

    console.log(response) // never goes there
  } catch (e) {
    console.error(e) // or there
  }

  return true
}
````

```
⚡️  [log] - purchase
⚡️  [log] - {"description":"Aide Vibes LGBTQ à accueillir plus de monde !","price":4.99,"identifier":"supporter_v2_one_month","introPrice":null,"subscriptionPeriod":"P1M","discounts":[],"productType":"NON_CONSUMABLE","productCategory":"SUBSCRIPTION","priceString":"4,99 €","currencyCode":"EUR","title":"Abonnement Supporter (1 mois)"}
````

Thank you

**Comment by tonidero** [comment]
Hi @TheotimeColin, thanks for reaching out!

One thing, could you try updating the call to:
```typescript
const response = await Purchases.purchaseStoreProduct({
  product: product
})
```
I'm not sure if it would work without the named parameter.

If that doesn't work, could you enable debug logs and sent them to us? You can enable debug logs calling
`await Purchases.setLogLevel({ level: LOG_LEVEL.DEBUG });` before calling `Purchases.configure`

**Comment by TheotimeColin** [comment]
Oooh, I was actually trying out another module and I had the exact same problem. I stumbled upon https://github.com/glassfy/capacitor-plugin-glassfy/issues/10 and it solved the issue for RevenueCat too!

This is for Vue/Nuxt users, product has to be wrapped in `toRaw` for it to work. Example 

```js
const response = await Purchases.purchaseStoreProduct({
  product: toRaw(product)
})
````

**Comment by tonidero** [comment]
Oh nice! Glad to know it. Thanks for sharing the fix!
