### ISSUE TITLE
What's the status of this plugin?

### ISSUE THREAD

**Issue by mcfarljw** [RevenueCat/purchases-capacitor#104]
I have several Capacitor apps using RevenueCat and have been using https://github.com/RevenueCat/cordova-plugin-purchases because it's the only thing mentioned in the RevenueCat docs:

https://www.revenuecat.com/docs/reference
https://www.revenuecat.com/docs/installation

Is this ready for production usage or still in development?

**Comment by tonidero** [comment]
Hi @mcfarljw, this plugin is currently on a testing phase but it has all functionality implemented. We plan to release a stable version and add it to the RevenueCat docs soon.

While this is still on beta and there may be issues, we don't expect any major changes at this point. So feel free to use it for your capacitor apps! I will update this issue once we've released the docs which should happen soon.

**Comment by mcfarljw** [comment]
Thanks for the update! I'll switch over and see how things go. It'll certainly be much nicer to be on an official Capacitor app.

**Comment by basvdijk** [comment]
@mcfarljw are there any plans to update https://www.revenuecat.com/docs/ionic with the Capacitor plugin instead of Cordova?

**Comment by mcfarljw** [comment]
@basvdijk think you want to as @tonidero as I'm not affiliated with RevenueCat. But it sounds like they plan on updating the docs when it's ready for primetime.

> We plan to release a stable version and add it to the RevenueCat docs soon.

**Comment by basvdijk** [comment]
@tonidero can you give an estimate on "soon"? We probably going to implement RC for our app. Docs would be a great start and save tons of time figuring out with the current docs.

**Comment by riderx** [comment]
@mcfarljw this plugin exists since a year, it was originally dev by me, and then transferred to Revenucat org who will take a better care of it :)
So it's not perfect but already in use in prod in apps since a year.

**Comment by tonidero** [comment]
Hi @basvdijk, sorry for the delay! The docs have been updated in https://www.revenuecat.com/docs/ionic. Please take a look and let us know if you run into any issues!

We still haven't released a stable version, but unless anything strange comes up, it should be within a couple of weeks.

**Comment by aboedo** [comment]
Hey folks, we forgot to update here: the plugin is now stable, although like @riderx mentioned, it's been usable in production for a year. 
It's now the official RevenueCat plugin, and it gets updates often. 

I'm closing out this issue for now, but let me know if you have any questions!
