### ISSUE TITLE
What version of Android Billing does this plugin use?

### ISSUE THREAD

**Issue by mepc36** [RevenueCat/purchases-capacitor#109]
Sorry, not an android person (I use the package for capacitor). Self-explanatory question. Thank you! I will report back if I find it. 

Mainly asking so I know if I will be compliant with Google's new post-2023-10-01 requirement that apps use Android Billing v5. See here for more details:

https://developer.android.com/google/play/billing/deprecation-faq

**Comment by mepc36** [comment]
Migration docs say it uses v5 here:

https://github.com/RevenueCat/purchases-capacitor/blob/main/migrations/v6-MIGRATION.md?plain=1#L7

Still looking for where it indicates the version in the code though...

**Comment by tonidero** [comment]
Hi @mepc36. This plugin indeed uses BC5. As you can see here: https://github.com/RevenueCat/purchases-capacitor/blob/main/VERSIONS.md we depend on `purchases-hybrid-common` version `6.1.2` which in turn depends on `purchases-android` `6.9.4`. You can see the biling client version we use here: https://github.com/RevenueCat/purchases-android/blob/6.9.4/gradle/libs.versions.toml#L5

Going to close this, but feel free to ask if you have more questions

**Comment by mepc36** [comment]
You're the best, thanks for answering this @tonidero !
