### ISSUE TITLE
CocoaPods could not find compatible versions for pod "PurchasesHybridCommon"

### ISSUE THREAD

**Issue by Gautammer** [RevenueCat/purchases-capacitor#114]
I migrated capgo plugin to purchases-capacitor plugin but getting errors in ios 
i am using ionic capacitor with all the latest version packages.
Here is what i am getting in terminal after running npx cap sync ios: 

```
[!] CocoaPods could not find compatible versions for pod "PurchasesHybridCommon":
        In Podfile:
        RevenuecatPurchasesCapacitor (from
        `../../node_modules/.pnpm/@revenuecat+purchases-capacitor@6.0.0_@capacitor+core@5.4.0/node_modules/@revenuecat/purchases-capacitor`)
        was resolved to 6.0.0, which depends on
        PurchasesHybridCommon (= 6.1.3)
        
        None of your spec sources contain a spec satisfying the dependency:
        `PurchasesHybridCommon (= 6.1.3)`.
        
        You have either:
        * out-of-date source repos which you can update with `pod repo update` or with `pod
        install --repo-update`.
        * mistyped the name or version.
        * not added the source repo that hosts the Podspec to your Podfile.
```

Please help

**Comment by jakeluo734** [comment]
in terminal, go to your ios/App folder, type: pod repo update, then: pod update PurchasesHybridCommon. Doing so will update the components needed.

**Comment by Gautammer** [comment]
Thanks @jakeluo734 your answer worked for me but first i had to run : 
`sudo arch -x86_64 gem install ffi`
Then
`arch -x86_64 pod install`
Then
`pod update PurchasesHybridCommon`
Then 
`npx pod-install
`

**Comment by Gautammer** [comment]
> Thanks @jakeluo734 your answer worked for me but first i had to run : `sudo arch -x86_64 gem install ffi` Then `arch -x86_64 pod install` Then `pod update PurchasesHybridCommon` Then `npx pod-install `

in ./ios/App
