### ISSUE TITLE
DOC Bugs: No Sample app for Ionic/Angular/Capacitor

### ISSUE THREAD

**Issue by Sampath-Lokuge** [RevenueCat/purchases-capacitor#121]
Hi,

I can't yet see the `Ionic/Angular/Capacitor` sample app on your official doc. So when will we have it there? Thanks!

Ref: https://www.revenuecat.com/docs/sample-apps

And I cannot see Ionic/Capacitor here too: https://www.revenuecat.com/docs/getting-started#%EF%B8%8F-reacting-to-subscription-status-changes

**Comment by tonidero** [comment]
Hi @Sampath-Lokuge, thanks for reporting. The docs have been updated with Capacitor samples. Going to close this but please let us know if you find anything else!

**Comment by tonidero** [comment]
Hi @Sampath-Lokuge, yeah, we have in our backlog tasks to add more samples to our capacitor plugin. We don't have a timeframe for it currently though. We will keep you updated when more samples have been added. Sorry for the inconvenience.
