### ISSUE TITLE
question: difference between `cycles` and `periodNumberOfUnits`

### ISSUE THREAD

**Issue by tafelnl** [RevenueCat/purchases-capacitor#122]
In the types the following two fields are returned on `PurchasesIntroPrice`: `cycles` and `periodNumberOfUnits`.

They seem very similar. From [the docs](https://www.npmjs.com/package/@revenuecat/purchases-capacitor#PurchasesIntroPrice):

`cycles`:
> Number of subscription billing periods for which the user will be given the discount, such as 3.

`periodNumberOfUnits`
> Number of units for the billing period of the discount.

Without any other information, these fields seem to be exactly the same. So what's the difference between the two, if any?

**Comment by tonidero** [comment]
Hi @tafelnl, that's a good question. Basically we're mapping what Apple/Google provide. To be more specific, Apple/Google gives you a period for which an intro price might take effect, say `P1M`, which translates to one month, but Apple/Google allow to specify that period multiple times, so for example, 3 times one month. In this example, `cycles` would be "3" and `periodNumberOfUnits` would be "1" from "1 month".

To be more specific:
- `cycles` correspond to:
  - Android: PricingPhase's billingCycleCount: https://developer.android.com/reference/com/android/billingclient/api/ProductDetails.PricingPhase#getBillingCycleCount()
  - iOS: The `SKProductDiscount`'s `numberOfPeriods` https://developer.apple.com/documentation/storekit/skproductdiscount/2936875-numberofperiods
- `periodNumberOfUnits` correspond to:
  - Android: The periods specify in the period in Google's PricingPhase object: https://developer.android.com/reference/com/android/billingclient/api/ProductDetails.PricingPhase#getBillingPeriod().   
  - iOS: The number of periods specified as the `SKProductDiscount` period object: https://developer.apple.com/documentation/storekit/skproductdiscount/2936870-subscriptionperiod
  
It's indeed a bit confusing, but hopefully that solves your question. Let me know if you are still not sure!

**Comment by tonidero** [comment]
Going to close this, but feel free to reopen if you have further questions.

**Comment by tafelnl** [comment]
Yes it totally make sense now. Thanks! I think the Google docs explain it quite well:

> Number of cycles for which the billing period is applied.
> For example, for formattedPrice $6.99 and billingPeriod P1M, if billingCycleCount is 2, the user will be charged $6.99/month for 2 months.

It might be worth it to consider adding a similar sentence to the API reference
