### ISSUE TITLE
bug: missing `productType` type on `PurchasesStoreProduct`

### ISSUE THREAD

**Issue by tafelnl** [RevenueCat/purchases-capacitor#123]
Title speaks for itself. In the query result json, `productType` is an available field on `PurchasesStoreProduct`. But it isn't reflected in the types

**Comment by vegaro** [comment]
Thank you for opening @tafelnl , you're correct, the types are missing. We are going to be adding that to the types

**Comment by tonidero** [comment]
Hi @tafelnl, we just released [6.1.0](https://github.com/RevenueCat/purchases-capacitor/releases/tag/6.1.0) that should add this field.

Going to close this but let us know if you run into issues!
