### ISSUE TITLE
bug: Missing `productPlanIdentifier` on `PurchasesEntitlementInfo`

### ISSUE THREAD

**Issue by wsamoht** [RevenueCat/purchases-capacitor#125]
I am currently working on converting over to Google's "new" subscription model and `PurchasesEntitlementInfo` seems to be missing `productPlanIdentifier`. Without it, we cannot know what base plan the user subscribed from. It was added to the Android SDK [here](https://github.com/RevenueCat/purchases-android/pull/849).

As as workaround, I am going to look at `customerInfo.activeSubscriptions` for the full ID.

**Comment by tonidero** [comment]
Hi @wsamoht, thanks for reporting this! As you said, the `productPlanIdentifier` is currently missing from the `PurchasesEntitlementInfo` model. We are working on it and will have a fix soon. Will update this ticket once it's fixed.

**Comment by tonidero** [comment]
Hi @wsamoht, we just released [6.1.0](https://github.com/RevenueCat/purchases-capacitor/releases/tag/6.1.0) that should add this field. 

Going to close this but let us know if you run into issues!
