### ISSUE TITLE
Can't build app with 7.0.0 (incomplete shouldShowInAppMessagesAutomatically and showStoreMessages)

### ISSUE THREAD

**Issue by BigBerny** [RevenueCat/purchases-capacitor#134]
I get three error messages with the following version (from Podfile.lock) when I want to build the app:
  - PurchasesHybridCommon (7.0.0):
    - RevenueCat (= 4.27.0)
  - RevenueCat (4.27.0)
  - RevenuecatPurchasesCapacitor (7.0.0):
    - Capacitor
    - PurchasesHybridCommon (= 7.0.0)

Error messages:
/path/ionic-pods/purchases-capacitor/ios/Plugin/PurchasesPlugin.swift:43:83 Extra argument 'shouldShowInAppMessagesAutomatically' in call
/path/ionic-pods/purchases-capacitor/ios/Plugin/PurchasesPlugin.swift:356:37 Type 'CommonFunctionality' has no member 'showStoreMessages'
/path/ionic-pods/purchases-capacitor/ios/Plugin/PurchasesPlugin.swift:360:37 Type 'CommonFunctionality' has no member 'showStoreMessages'

**Comment by tonidero** [comment]
Hi @BigBerny, those error messages seem to indicate you're using an old version of our PurchasesHybridCommon pod after upgrading to version 7.0.0. Unfortunately, I wasn't able to reproduce.

I'm not sure what platform you're running on, but could you try to find the `Podfile` in your iOS source code and run `pod update` to see if it updates to the latest version? 

If that doesn't work, please share the resulting logs from running that and the relevant parts of your `Podfile.lock` file if possible.

**Comment by jmholding-fynn** [comment]
@tonidero I was running into the same issue. Your suggestion on updating the podfile worked for me.

**Comment by BigBerny** [comment]
Same for us. Was an issue with using an outdated Podfile. 👍️
