### ISSUE TITLE
[iOS] purchasePackage is extremely slow

### ISSUE THREAD

**Issue by derWebdesigner** [RevenueCat/purchases-capacitor#136]
Hey there,

I just switched from the Cordova package to Capacitor and recognized that the following call is extremely slow (5-10 seconds) on iOS. On Android, I see the payment overlay almost immediately, but on iOS I even had to implement an additional loading spinner because nobody would expect it to still do something. I used the Capacitor switch to update the version as well, so I am not 100% sure if the switch caused the very slow reaction or the version itself.

`Purchases.purchasePackage({ aPackage: p })`

I tested it on an old iPhone 6s and a new iPhone 15, both were equally slow.

Thank you very much,
Manuel

**Comment by aboedo** [comment]
Hey @derWebdesigner, thanks for reporting. 

The sad news is that that's fairly normal in Sandbox in iOS, the OS itself just takes a pretty long time to kick off the payment flow. 

The good news is that in Production it's a bit better and certainly much more consistent (Sandbox has good and bad days, and some times it even depends on the account). 

You can get faster times for testing by using [StoreKit Configuration Files](https://www.revenuecat.com/docs/apple-app-store#ios-14-only-testing-on-the-simulator).

**Comment by derWebdesigner** [comment]
@aboedo Hey Andy, thank you for the quick feedback, I really appreciate it. I was just wondering because before the switch this wasn't the case. I will definitely try some external devices without a sandbox account to see how they behave.
