### ISSUE TITLE
Rejected from PlayStore for Collecting Advertising ID

### ISSUE THREAD

**Issue by yonkahlon** [RevenueCat/purchases-capacitor#138]
Since I migrated from the cordova library my app is being rejected from the PlayStore. Our app is targeted at kids, so we cannot collect that at all.

Is there a way to disable this? Couldn't find anything in the documentation.

![image](https://github.com/RevenueCat/purchases-capacitor/assets/13463301/200d1397-55b0-47d4-b683-b712eb0170ab)

**Comment by tonidero** [comment]
Hi @yonkahlon, we don't try to get advertising id nor any of that data unless you call [collectDeviceIdentifiers](https://www.npmjs.com/package/@revenuecat/purchases-capacitor#collectdeviceidentifiers). Are you calling that method? 

Additionally, we don't add the [required permission](https://support.google.com/googleplay/android-developer/answer/6048248?hl=en-GB) to get advertising id in Android 13+ to our sdk. Could you check whether this might be added by a different 3rd party library?

**Comment by yonkahlon** [comment]
Hi @tonidero :-)

Thanks for the feedback!

Yeah, I saw the collectDeviceIdentifiers method, and I'm not calling them. I'll dig around, maybe we've added another library since the last release was accepted.

**Comment by vegaro** [comment]
A good hint would be to take a look at the merged Android manifest of your app. Our library doesn't add the `AD_ID` permission automatically because of kids apps but maybe as you said there's another library adding it?

**Comment by yonkahlon** [comment]
@vegaro thanks! 

Through the merged Android manifest I found that "com.facebook.core" is being included. 

I'm Just struggling to figure out why it's being included. A dependency analysis doesn't show anything.

My capacitor plugins:

```
dependencies {
    implementation project(':capacitor-firebase-authentication')
    implementation project(':capacitor-app')
    implementation project(':capacitor-haptics')
    implementation project(':capacitor-keyboard')
    implementation project(':capacitor-share')
    implementation project(':capacitor-status-bar')
    implementation project(':capawesome-capacitor-screen-orientation')
    implementation project(':revenuecat-purchases-capacitor')

}
```

I'll keep digging though

**Comment by vegaro** [comment]
There's a Gradle scan tool that you might find useful to figure out which dependency is including `com.facebook.core`. To run it just add `--scan` to your Gradle build command. For example:

```
./gradlew assembleDebug --scan
```

Then it will send you a link with a website where it's easier to see what's going on with the dependencies

**Comment by yonkahlon** [comment]
I'm learning a lot here. Thank you @vegaro!

I think I found the culprit... It must be something in my config because it wasn't including this before.

![image](https://github.com/RevenueCat/purchases-capacitor/assets/13463301/fbc104e4-a45a-4394-96ac-713a11549ea1)

Anyways - this is clearly not a RevenueCat issue, so I'll close this. Again, thank you for the input!

**Comment by yonkahlon** [comment]
Hi @vegaro :-)

It looks like the issue with capacitor-firebase-authentication has been solved, but our app is still being rejected from the PlayStore.

There is no AD_ID permission in the manifests (I checked both the merged manifest & I've unzipped the bundle and checked there.)

I got this response from Google when I asked for more information:

> Step 1: Fix the policy violation with your app
> 
> During review, we found that your app violates the [Families Policy Requirements](https://support.google.com/googleplay/android-developer/answer/9893335#families-policy). We’ve identified that your app or an SDK in your app transmits identifier(s) that do not comply with our Families Policy. These identifiers may include, but are not limited to, Advertising ID.
> 
> For example, the destinations of Android Advertising ID transmission may include, but are not limited to, [[api2.branch.io](https://mentor.corp.google.com/api2.branch.io)].
> 
> Apps that solely target children, must not transmit the following:
> 
>     Android Advertising ID (AAID)
>     SIM Serial
>     Build Serial
>     BSSID
>     MAC
>     SSID
>     IMEI and/or IMSI

We don't use the Branch.io library (in previous versions we did, but haven't included it since we've migrated to Capacitor). Looking through RevenueCat's repositories, I see you do support Branch.io. Do you think there is any chance that the RevenueCat library is transmitting to branch.io?

I know it's a long shot, but I can't find any references to AD_ID or branch in the project.

**Comment by tonidero** [comment]
> Do you think there is any chance that the RevenueCat library is transmitting to branch.io?

@yonkahlon Our SDK won't transmit to branch.io directly. If you call `collectDeviceIdentifiers` and have added the relevant permissions, the `AD_ID` will be sent to our servers, and if you have enabled the branch.io integration in our dashboard, the value might be transferred in a server-to-server communication.

I'm guessing not but just to confirm, the branch sdk doesn't appear in the classpath in your android app correct?

**Comment by yonkahlon** [comment]
@tonidero yeah, I can't find any reference to branch in my build...

[Here is the URL](https://scans.gradle.com/s/4gnlxuluubwsg) to the build scan. Can you view it? 

I'm running out of ideas.  The major change I made was integrating with Stripe & moving from the cordova lib to the capacitor lib. Stripe is only in the webapp, so that shouldn't be the problem. (I don't see any references to it in the Android app). Without the AD_ID permission it shouldn't matter right?

I'm going to try and engage with Google to get more clarity. If that fails I'll try revert back to the cordova and try again.

**Comment by yonkahlon** [comment]
Oh my goodness!

I got feedback from Google:

> Before resubmitting your app for further review, please make sure to DEACTIVATE the non compliant [App Bundle Version: 66, Track: Open Testing] and increment the version number of App Bundle. 

The Open Testing track is paused, so I didn't think that mattered. That App Bundle is years old... There must have been a policy change recently.

Anyways - again - thank you for the help :-)

**Comment by tonidero** [comment]
@yonkahlon Nice! Hope that passes review!

@viniciusmiquelao Are you using this capacitor plugin? If so, what version? Also, can you confirm you're not using other libraries that would fetch the advertising id? RevenueCat won't fetch the advertising ID unless you call `collectDeviceIdentifiers`.
