### ISSUE TITLE
Unable to get products/offerings

### ISSUE THREAD

**Issue by Martijn0405** [RevenueCat/purchases-capacitor#165]
Using the migration guide, I tried many ways to retrieve products and offerings from my account. I used both my secret API key and also my public app-specific API key for android to test. The getProducts method returns {products: []} (while I have 3 products as parameters and on revenuecat) with either key. And the getOfferings method returns a different error with either key.

Here is my implementation of getProducts:
`await Purchases.getProducts({
  productIdentifiers: [
    "id1",
    "id2",
    "id3"
  ],
  type: PRODUCT_CATEGORY.NON_SUBSCRIPTION
})`

The getOfferings errors are as follows. With the secret API key:
`Uncaught (in promise) Error: There was an unknown backend error.`
and with the google/android public key:
`Uncaught (in promise) Error: There is an issue with your configuration. Check the underlying error for more details.`
the underlying error being:
`ConfigurationError`

Which is the key to use and what parameters/functions/other things am I doing wrong or are missing?

**Comment by aboedo** [comment]
@Martijn0405 the secret API key should never be used within your app, it's meant only for server-to-server interactions, so that's why there's a backend error for that one (although we should improve the message to make that clearer). 

For the public key error, there should be more information available in the logs, could you share more of the log messages?

**Comment by Martijn0405** [comment]
Hi, I was only see the error from the response: `ConfigurationError`. How would I access the logs with more information?

**Comment by Martijn0405** [comment]
I looked at the response of configure(), and it was -1, using the Google key on an Android test device.
