### ISSUE TITLE
Error: "Purchases" plugin is not implemented on ios

### ISSUE THREAD

**Issue by Mitcheljager** [RevenueCat/purchases-capacitor#182]
I am running this plugin in a Svelte app using Capacitor via the xcode iOS simulator. When trying to do anything at all I get an error `Error: "Purchases" plugin is not implemented on ios`. 

This is all I'm doing:
```js
import { LOG_LEVEL, PURCHASES_ERROR_CODE, Purchases } from '@revenuecat/purchases-capacitor'

export async function configureRevenueCat() {
  console.log('configure revenue cat')

  await Purchases.setLogLevel(LOG_LEVEL.DEBUG)

  await Purchases.configure({ apiKey: '...' })
}
```

I'm using version `7.3.2` with `@capacitor/core` at `5.4.1` and `@capacitor/app` at `5.0.6`

I've got the exact same set up (minus a different api key) on Android and there it works fine.

Any pointers on what I'm doing wrong would be much appreciated!

**Comment by michaelAtRC** [comment]
Hey @Mitcheljager ,

Could you send debug logs that reproduce this? You can enable debug logs by following [this guide](https://docs.revenuecat.com/docs/debugging#section-debugging). After they're enabled you'll see logs like this in the console:

[Purchases] - DEBUG: No cached entitlements, fetching
[Purchases] - DEBUG: GET /v1/subscribers/<APP_USER_ID> 200
[Purchases] - DEBUG: Purchaser info updated, sending to delegate


Please ensure the debug logs include the entire app life-cycle, including the messages printed during initialization of the SDK. The more information you include here, the better we'll be able to help.

Let me know if you have any questions!

**Comment by Mitcheljager** [comment]
Welp, I changed nothing and it works now, I have no idea what I did but it must have been a me issue. Sorry about that, thanks for the help though!

**Comment by michaelAtRC** [comment]
Hey @Mitcheljager!

Glad to hear things are now working as planned.
