### ISSUE TITLE
DataCloneError: The object can not be cloned.

### ISSUE THREAD

**Issue by braincomb** [RevenueCat/purchases-capacitor#212]
Hello,

We've been testing on Android with no issues whatsoever until we started testing on iOS when suddenly we got a `Error: Unhandled Promise Rejection: DataCloneError: The object can not be cloned.` error.

After some digging around we remembered that, since we are using Vue, we need to use `toRaw()` to convert Proxy objects back to original, which fixed the issue.

I also found this [comment ](https://github.com/RevenueCat/purchases-capacitor/issues/141#issuecomment-1794384240) from @tonidero from last year:

> We are still trying to figure out why it would work on Android though...

Here's our take on it from the error we got from Capacitor, it seems that the reason it works on Android, without requiring to use `toRaw()` is because it already stringifies the object when passing it to native layer (line 799 below), but for some reason it doesn't for iOS (line 812).

So my question is, is there any reason why RevenueCat SDK can't just do `JSON.parse(JSON.stringify(data))` when receiving data from the user before passing it along to the native layer. That way you wouldn't have to force Vue users to use `toRaw()` and avoid common pitfalls.

```
if (getPlatformId(win) === 'android') {
                // android platform
                postToNative = data => {
                    var _a;
                    try {
                        win.androidBridge.postMessage(JSON.stringify(data)); // line 799
                    }
                    catch (e) {
                        (_a = win === null || win === void 0 ? void 0 : win.console) === null || _a === void 0 ? void 0 : _a.error(e);
                    }
                };
            }
            else if (getPlatformId(win) === 'ios') {
                // ios platform
                postToNative = data => {
                    var _a;
                    try {
                        data.type = data.type ? data.type : 'message';
                        win.webkit.messageHandlers.bridge.postMessage(data); // line 812
                    }
                    catch (e) {
                        (_a = win === null || win === void 0 ? void 0 : win.console) === null || _a === void 0 ? void 0 : _a.error(e);
                    }
                };
            }
```

_(Using v7.4.0)_

**Comment by tonidero** [comment]
Hi @braincomb, sorry for the delay!

> is because it already stringifies the object when passing it to native layer

Thanks for investigating that! That indeed seems like it could be causing those issues. Thank for taking the time to debugging this! 

> is there any reason why RevenueCat SDK can't just do JSON.parse(JSON.stringify(data)) when receiving data from the user before passing it along to the native layer

As for your suggested fix, currently the Typescript layer is a simple interface without any logic that calls the corresponding methods in the native layer. We would need to modify this interface to write a wrapper in the typescript side that actually performs this transformation. Another thing to consider, is that this would be a performance hit in all users of the plugin, even if you don't need to use `toRaw`. Not to say there are no ways to work around these though. We will consider our options with this and reach back. 

Thanks again for investigating this!
