### ISSUE TITLE
Version mismatch between installed SDK and RevenueCat customer dashboard

### ISSUE THREAD

**Issue by braincomb** [RevenueCat/purchases-capacitor#224]
While testing I've noticed that the versions mismatch.

npm package version: 
`"@revenuecat/purchases-capacitor": "^7.4.0"`

In customer dashboard:
`capacitor (android SDK 7.3.1)`

Is that displaying something different or an unintended bug?

**Comment by tonidero** [comment]
Hi @braincomb, thanks for reaching out!

That actually refers to the underlying native SDK for android or iOS. Our capacitor SDK is just a wrapper around those native SDKs. That means that user was last seen using android SDK 7.3.1. You can see how these versions match capacitor here: https://github.com/RevenueCat/purchases-capacitor/blob/main/VERSIONS.md

Going to close this but feel free to reopen and lmk if you have any other questions!
