### ISSUE TITLE
Support for DEFERRED in PRORATION_MODE

### ISSUE THREAD

**Issue by braincomb** [RevenueCat/purchases-capacitor#228]
Hello,

We have multiple tiers and Google recommends using `DEFERRED` mode when downgrading a user. DEFERRED in mentioned your documentation, but I don't believe the SDK actually supports it.

Are there any plans to support `DEFERRED` proration mode? If not, what would be a good workaround or the next best choice?

Thanks.

**Comment by mshmoustafa** [comment]
I should mention that we support older SDKs with bug and security fixes, but you might not have all of the latest features on an old SDK so we recommend updating to the most recent if you can.

**Comment by braincomb** [comment]
> I should mention that we support older SDKs with bug and security fixes, but you might not have all of the latest features on an old SDK so we recommend updating to the most recent if you can.

Thanks for the info. I definitely want to stay with the latest SDK to support some of the features we want. It would also be preferable to have consistent behavior between the two platforms which means using `DEFERRED` on Android when downgrading a user from a higher tier to a lower tier.

Are there any plans to support this in the future?

**Comment by mshmoustafa** [comment]
There are plans to support deferred in the future but as I remember there were some limitations with some Google APIs that would be required to do so. We communicate with Google often and they're always updating their system so it's definitely something we reconsider periodically.

**Comment by mshmoustafa** [comment]
I'll tag an engineer on our mobile team @aboedo so that this is on his radar in case there's anything else he'd like to add

**Comment by aboedo** [comment]
Yeah, pretty much what @mshmoustafa said - we do plan to support it, but we ran into a few limitations on Google's APIs as well as bugs we reported. We do intend to retest and solve the issues, but we don't have an ETA we can share just yet.

**Comment by mshmoustafa** [comment]
Hi all, I'll close this topic for now but if we have anything new to share we'll likely announce it in our monthly email newsletter.
