### ISSUE TITLE
Feature Request: Web

### ISSUE THREAD

**Issue by robmarshall** [RevenueCat/purchases-capacitor#230]
Hey,

It would be great if I could access subscription status from the web, off a user ID. I am using plugin across all platforms (web, app store, google play) and currently need to do my own server-side/web hooks to get this info to be used on the web.

If everything could be wrapped up in this one app, would make life a lot easier.

Thanks,
Rob

**Comment by michaelAtRC** [comment]
Hey Rob, 

We have our [/subscribers](https://www.revenuecat.com/docs/api-v1#tag/customers/operation/subscribers) API endpoint which should help with this for you. Hitting this endpoint gets the latest [Customer Info](https://www.revenuecat.com/docs/api-v1#tag/customer_info_model) for the customer with the given App User ID, or creates a new customer if it doesn't exist.

Let me know if that helps!
