### ISSUE TITLE
Cocoapods support for Privacy Manifest

### ISSUE THREAD

**Issue by dmitry-salnikov** [RevenueCat/purchases-capacitor#238]
Actually there's the same issue as in Flutter. The fix in the iOS repo: https://github.com/RevenueCat/purchases-ios/pull/3772

So, the point is - please integrate the 4.40.0 iOS version into Capacitor plugin, which has fixed the privacy manifest being absent in the app bundle when integrating via Cococapods.

**Comment by lomchik** [comment]
+

**Comment by aboedo** [comment]
Hey folks, thanks for reporting! The good news is that we're already on it! 
#239 updates our iOS SDK to 4.40.0, which in turn adds the Privacy Manifest. It should go out in the next couple of days.

**Comment by dmitry-salnikov** [comment]
Great, thanks! looking forward to it!

**Comment by EinfachHans** [comment]
This is published already and can be closed correct?

**Comment by dmitry-salnikov** [comment]
@EinfachHans yes, correct
