### ISSUE TITLE
Purchases.purchasePackage does nothing

### ISSUE THREAD

**Issue by meevly** [RevenueCat/purchases-capacitor#243]
Hi there,

I have VueJS + Capacitor app on iOS and `Purchases.purchasePackage` does nothing - as in example, `start purchase` gets logged but then it seems to just hang and there's no further output, no sign in screen comes up, nothing. I've tried it on both XCode and on my device with TestFlight, I've tried replacing logic to use `purchaseStoreProduct` instead - didn't help either. I've checked that I pass proper package and it exists, etc. I've double checked all configuration like a million times (it fetches proper offerings, packages & products). What confuses me even more is that in other place I call `Purchases.restorePurchases()` and it seems to work (at least it throw sign in dialog on XCode build). Any ideas? Is there any way to debug or possible causes? I also don't think it's conflicting with another dependency as I don't use a lot of them..

```
methods: {
    async purchaseSubscription() {
      this.loading = true;
      const packageToBuy = this.packages.find(p => p.identifier === this.checked);

      try {
        console.log('start purchase')
        const purchaseResult = await Purchases.purchasePackage({ aPackage: packageToBuy });
        console.log('purchase result', purchaseResult)
      } catch (error) {
        console.log('test');
        console.log(error);
      }
    },
},
```

**Comment by tonidero** [comment]
Hi @meevly,

Are you using VueJS reactivity APIs? If so, you might need to call `toRaw` on the `package` parameter: https://vuejs.org/api/reactivity-advanced.html#toraw.

If that doesn't work, could you send us your debug logs so we can take a look?

**Comment by meevly** [comment]
@tonidero oh. my. god. I'm stupid as hell 🤦I have even seen that big warning box multiple times in docs. I haven't tried the fix yet but it's very likely the issue. As I realize more and more - if you can't find solution on Google, it must be something very stupid of yours 🥲  Thank you so much!

**Comment by tonidero** [comment]
No worries at all!This is something we want to address at some point, but for now, the fix is to use `toRaw` yeah. 

Going to close this but feel free to reopen if the issue persists!

**Comment by Jdubedition** [comment]
Thank you for posting this issue and the toRaw() answer, this is exactly what was causing my Vue Capacitor app purchase to not return.  I have one package available, so I wrapped it like this: `toRaw(offerings.value.current.availablePackages[0])`
