### ISSUE TITLE
Unable to make a purchase or get any output

### ISSUE THREAD

**Issue by timgavin** [RevenueCat/purchases-capacitor#68]
Thanks for this package.

I followed [the tutorial](https://capgo.app/blog/in-app-purchases-capacitor/) and absolutely nothing happens when attempting to make a purchase. Not sure if I'm implementing it incorrectly (instructions unclear to me), or the package doesn't support my versions...

Ionic 7
Capacitor 5
Angular 16

I have a button on my Settings page to make a one-time purchase. When clicking the button I attempt to make a purchase, which for now is just trying to output something to the logs to see what's happening...

#### settings.page.ts

```typescript
import { Package } from '@capgo/capacitor-purchases';

makePurchase() {
    console.log('making a purchase'); // this prints to the log
    const purchase = async (p: Package): Promise<PurchaserInfo | null> => {
        try {
            console.log('inside try block'); // this never prints to the log
        } catch (e) {
            console.error('error', e); // this doesn't print either
        }
    }
}
```

#### app.module.ts

```typescript
import { IonicModule, IonicRouteStrategy, Platform } from '@ionic/angular';
import { CapacitorPurchases } from '@capgo/capacitor-purchases';

export class AppModule {
    constructor(private platform: Platform) {
        CapacitorPurchases.setDebugLogsEnabled({ enabled: true }).then();
        if (this.platform.is('ios')) {
            CapacitorPurchases.setup({ apiKey: 'appl_********' }).then(res => { // <-- I use my real API key
                const offerings = CapacitorPurchases.getOfferings();
            });
        } else if (this.platform.is('android')) {
            CapacitorPurchases.setup({ apiKey: 'goog_******' }).then();
        }
    }
}
```

I should note that the code in`app.module.ts` was initially in the `settings.page.ts` constructor, and I could print the products to the log, so the plugin is installed.. it just never printed anything to the logs after setting `const purchase` so I moved it thinking I'd installed it correctly..

What am I doing wrong?

**Comment by riderx** [comment]
Do you try in simulator or real device ?
Do you price are already released in app store ?
If no in any of this question i suggest to fix that, apple has a tendency to be very annoying with inapp purchases.

**Comment by timgavin** [comment]
@riderx I tried on the iOS simulator, and yes, I have products configured and approved in the App Store. They are set up with RevenueCat and everything is good to go, just can't get the plugin to work.

**Comment by riderx** [comment]
Do you see any logs in xcode about in App purchases ?
Usually i test in real device, Apple had long time simulator not working, so i don't trust it.

**Comment by timgavin** [comment]
I deleted the iOS folder and reinstalled, then synched. I do not see any errors in the Safari console, but I do see one in Xcode, so progress!

```
Stored property 'bundle' of 'Sendable'-conforming class 'BundleSandboxEnvironmentDetector' has non-sendable type 'Bundle'
```

This is coming from Pods > RevenueCat > SandboxEnvironmentDetector > SandboxEnvironmentDetector

```swift
//
//  Copyright RevenueCat Inc. All Rights Reserved.
//
//  Licensed under the MIT License (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      https://opensource.org/licenses/MIT
//
//  SandboxEnvironmentDetector.swift
//
//  Created by Nacho Soto on 6/2/22.

import Foundation

/// A type that can determine if the current environment is sandbox.
protocol SandboxEnvironmentDetector: Sendable {

    var isSandbox: Bool { get }

}

/// ``SandboxEnvironmentDetector`` that uses a `Bundle` to detect the environment
final class BundleSandboxEnvironmentDetector: SandboxEnvironmentDetector {

    private let bundle: Bundle  <--- ISSUE IS ON THIS LINE

    init(bundle: Bundle = .main) {
        self.bundle = bundle
    }

    var isSandbox: Bool {
        guard let path = self.bundle.appStoreReceiptURL?.path else {
            return false
        }

        // `true` for either `macOS` or `Catalyst`
        let isMASReceipt = path.contains("MASReceipt/receipt")
        if isMASReceipt {
            return path.contains("Xcode/DerivedData")
        } else {
            return path.contains("sandboxReceipt")
        }
    }

    #if DEBUG
    // Mutable in tests so it can be overriden
    static var `default`: SandboxEnvironmentDetector = BundleSandboxEnvironmentDetector()
    #else
    static let `default`: SandboxEnvironmentDetector = BundleSandboxEnvironmentDetector()
    #endif

}

#if swift(<5.8)
// `Bundle` is not `Sendable` as of Swift 5.7, but this class performs no mutations.
extension BundleSandboxEnvironmentDetector: @unchecked Sendable {}
#endif
```
<img width="1200" alt="Screenshot 2023-06-19 at 7 26 52 AM" src="https://github.com/Cap-go/capacitor-purchases/assets/1012049/e956b070-147e-4953-a273-b8a607ec21bf">

**Comment by aboedo** [comment]
Hey folks, it's been quite a while, so I'm closing out this issue, but feel free to reopen if you're still facing issues! Although I'd recommend updating to the latest version first 😅 

The Sendable issues have been figured out on iOS. As for simulator, you also need to [create a StoreKit Configuration file](https://www.revenuecat.com/docs/apple-app-store#step-1-add-a-storekit-configuration-file) and set it in the scheme, otherwise you won't be able to make purchases on the simulator.
