### ISSUE TITLE
Android customerInfo key changed

### ISSUE THREAD

**Issue by RyVeata** [RevenueCat/purchases-capacitor#71]
When implementing this plugin for Android 10+ using version 2.8.0 and Capacitor 5 the `addListener('purchasesUpdate', ...)` function returns an object with an odd key for the customerInfo.  For me the current response returns:

`{
purchasecustomerInforInfo: {...}
purchases: {...}
}`

whereas the result is documented as:

`{
customerInfo: {...}
purchases: {...}
}`

The documented version is correct for iOS and works fine, I've only seen this issue on Android.  For now I've just worked around it by checking the platform and using the relevant key, but it would be good to see this made consistent again in future.

**Comment by riderx** [comment]
Hey @RyVeata thanks for the report, i'm sorry i didn't answer faster i forgot you, i will fix this.

**Comment by riderx** [comment]
[5.0.5](https://github.com/Cap-go/capacitor-purchases/tree/5.0.5) should fix your issue

**Comment by aboedo** [comment]
I'm tentatively closing this issue, let us know if you're running into issues still!
