### ISSUE TITLE
Why this plugin is not mentioned on official doc?

### ISSUE THREAD

**Issue by Sampath-Lokuge** [RevenueCat/purchases-capacitor#78]
Hi,

Can you tell me why this plugin has not been mentioned on Revenuecat's official doc here: https://www.revenuecat.com/docs/ionic

**Comment by riderx** [comment]
Hey @Sampath-Lokuge The plugin has been made by me not RC that why it's still not in they doc.

Good news is they saw people started to use this package and they like it.
They will to take the lead on it and integrate it in they ORG and Doc. 
We don't have timeline for this it look a bit busy on they side, but still mark on TODO.

You can safely use this plugin :)

**Comment by tonidero** [comment]
Hi! Yes! as @riderx said, RevenueCat has taken over this plugin and we have just released the first beta of the plugin with version `6.0.0-beta.1`. We are working in adding documentation to the official docs, and should be ready soon.

Going to close this for now.
