### ISSUE TITLE
Missing a lot of functions like

### ISSUE THREAD

**Issue by Aviho-M** [RevenueCat/purchases-capacitor#80]
getProducts ,collectDeviceIdentifiers ,getPurchaserInfo and more

**Comment by riderx** [comment]
getPurchaserInfo  is now getCustomerInfo as they migrated to new SDK.
The 2 others one are missing, it's pretty easy to add them since we bridge from the common SDK.
I don't have much space to add them right now but maybe @vegaro or the Team at RC could check :)

**Comment by riderx** [comment]
@Aviho-M collectDeviceIdentifiers are implemented already you have to set it in the config object of the plugin:
```json
{
"CapacitorPurchases": {
  "collectDeviceIdentifiers": true
  }
}
```

**Comment by riderx** [comment]
i have add getProducts :)

**Comment by tonidero** [comment]
Hi everyone! We have released the first beta of the plugin after RevenueCat took over with version `6.0.0-beta.1`. This adds many of the missing functions and mimicks more closely our API in the other RC plugins. Please take a look and let us know if you have any issues or feedback. Going to close this issue for now.
