### ISSUE TITLE
Development setup

### ISSUE THREAD

**Issue by sourcecodeit** [RevenueCat/purchases-capacitor#90]
I'm having a hard time implementing in-app purchases with capacitor, what is the best setup for developing a capacitor app with in-app purchases?

The problem is I can't get real data (for example the list of my app offerings) because RevenueCat mocks data in web version. That means that every time I need to test real data I have to build e run on my phone and it takes too much.

My setup is:

- Nuxt 3
- Vite
- Capacitor

I normally run 

`npm run dev`

so I have hot reloads but as I said, this way I can't test in app purchases. Is there a way we can have hot reload + in app purchases without mocked data?

**Comment by riderx** [comment]
Hello in web it's this plugin who mock the data, not revenuecat.
This plugin has to run in mobile app to be tested.
What i suggest is to dev the UI with live reload and then when ready do the painful process with build in mobile.
That sadly the only way.
You can do hot reload into the mobile app as well with few restrictions:
https://capacitorjs.com/docs/v4/guides/live-reload

**Comment by sourcecodeit** [comment]
Thanks. I did as you suggested, in the end is less painful that what I thought. Thanks for the explanation.
