### ISSUE TITLE
Subscription upgrade, downgrade and management features

### ISSUE THREAD

**Issue by bartan34** [RevenueCat/purchases-capacitor#93]
Are there any plans to add RevenueCat's subscription upgrade and downgrade controls with the upcoming SDK 6+ update?

**Comment by tonidero** [comment]
Hi @bartan34! Yes, that's included in version `6.0.0-beta.1`. This update points to the latest changes in the iOS and Android SDKs. There are some migration docs here: https://github.com/RevenueCat/purchases-capacitor/blob/main/migrations/v6-MIGRATION.md. We are working in some public documentation right now which should be ready soon.

Please try it out and let us know if you have any issues or feedback!

Going to close this issue for now.
