### ISSUE TITLE
allowedCommonJsDependencies necessity?

### ISSUE THREAD

**Issue by woutersteven2020** [RevenueCat/purchases-capacitor#98]
Good morning,

When compiling I'm getting:

`"Warning: c:\.....\node_modules\@revenuecat\purchases-capacitor\dist\esm\definitions.js depends on '@revenuecat/purchases-typescript-internal'. CommonJS or AMD dependencies can cause optimization bailouts."`

I can resolve this message by suppressing it in angular.json by adding it to the allowedCommonJsDependencies array, but that's not ideal. 

I was wondering if the new beta version would address this, or if it will remain like this.

**Comment by tonidero** [comment]
Hi @woutersteven2020, sorry for the delay, we are studying options here. We will update this issue when we have come up with a solution.

**Comment by tonidero** [comment]
Hi @woutersteven2020, we have fixed this issue in `6.0.0-beta.2`. Closing this issue but please feel free to reopen if you are still running into issues. Thanks for reporting it!
